# HoloLens 2 Device Configuration
# 작성일: 2025-08-30
# 작성자: Dongjune Chang
# 용도: HoloLens 2 디바이스 정보 및 Device Portal 접속 정보 관리

# Device Portal 공통 인증 정보
device_portal:
  username: "test"
  password: "1a2s3D4F5G*"
  port: 443  # HTTPS 기본 포트
  protocol: "https"
  
  # API 엔드포인트
  endpoints:
    live_stream: "/api/holographic/stream/live.mp4"
    device_info: "/api/os/info"
    battery_status: "/api/power/battery"

# 스트리밍 품질 프리셋 (Python MRC 프록시용)
streaming_presets:
  high:
    resolution: "1920x1080"
    framerate: 60
    bitrate: 10000000  # 10 Mbps
    
  medium:
    resolution: "1280x720"
    framerate: 30
    bitrate: 5000000  # 5 Mbps
    
  low:
    resolution: "640x480"
    framerate: 15
    bitrate: 2000000  # 2 Mbps

# HoloLens 2 디바이스 목록
# 물리적 디바이스 정보 + 네트워크 설정 참조
devices:
  "HOLOLENS-EP9MKK":
    owner: "dongjune_chang"
    device_ip: "192.168.10.108"  # Device Portal 접속용
    streaming_preset: "medium"
    # 네트워크 설정 (network_config.yaml 참조)
    ros_server: "nchr_xarm5"      # ros_config.servers 참조
    riley_mode: "zmq_local"       # riley_config.modes 참조
    streaming_mode: "zmq_local"   # streaming_config.modes 참조
    user_location: "on_site"      # on_site | remote

  "HOLOLENS-G4NTC8":
    owner: "hyunglae_lee"
    device_ip: "192.168.10.128"
    streaming_preset: "medium"
    ros_server: "nchr_xarm5"
    riley_mode: "http_ngrok"      # GPU 서버 사용
    streaming_mode: "zmq_aggregator"  # 중앙 집계
    user_location: "remote"       # Remote viewer

  "HOLOLENS-OG5M61":
    owner: "youngsoo_park"
    device_ip: "172.14.1.8"
    streaming_preset: "medium"
    ros_server: "chicago_home"
    riley_mode: "zmq_local"
    streaming_mode: "zmq_local"
    user_location: "on_site"      # On-site at Chicago

  # Unity Editor / Desktop 테스트용
  "UNITY_EDITOR":
    owner: "developer"
    device_ip: "127.0.0.1"
    streaming_preset: "medium"
    ros_server: "chicago_home"
    riley_mode: "zmq_local"
    streaming_mode: "zmq_local"
    user_location: "on_site"      # Editor는 on-site 테스트용

  "MSI":
    owner: "dongjune_chang"
    device_ip: "127.0.0.1"
    streaming_preset: "high"
    ros_server: "chicago_home"
    riley_mode: "zmq_local"
    streaming_mode: "zmq_local"
    user_location: "remote"       # Desktop은 remote로 간주

  # 기본값 (디바이스명 감지 실패시)
  default:
    owner: "unknown"
    device_ip: "127.0.0.1"
    streaming_preset: "medium"
    ros_server: "localhost"
    riley_mode: "zmq_local"
    streaming_mode: "zmq_local"
    user_location: "on_site"