# HoloLens 2 Device Configuration
# 작성일: 2025-08-30
# 작성자: Dongjune Chang
# 용도: HoloLens 2 디바이스 정보 및 Device Portal 접속 정보 관리

# Device Portal 공통 인증 정보
device_portal:
  username: "test"
  password: "1a2s3D4F5G*"
  port: 443  # HTTPS 기본 포트
  protocol: "https"
  
  # API 엔드포인트
  endpoints:
    live_stream: "/api/holographic/stream/live.mp4"
    device_info: "/api/os/info"
    battery_status: "/api/power/battery"

# 스트리밍 품질 프리셋 (Python MRC 프록시용)
streaming_presets:
  high:
    resolution: "1920x1080"
    framerate: 60
    bitrate: 10000000  # 10 Mbps
    
  medium:
    resolution: "1280x720"
    framerate: 30
    bitrate: 5000000  # 5 Mbps
    
  low:
    resolution: "640x480"
    framerate: 15
    bitrate: 2000000  # 2 Mbps

# HoloLens 2 디바이스 목록 (간소화)
devices:
  "HOLOLENS-EP9MKK":
    owner: "dongjune_chang"
    device_ip: "192.168.10.108"  # Device Portal 접속용
    streaming_preset: "medium"
    
  "HOLOLENS-G4NTC8":
    owner: "hyunglae_lee"
    device_ip: "192.168.10.128"  # Device Portal 접속용
    streaming_preset: "medium"
    
  "HOLOLENS-OG5M61":
    owner: "youngsoo_park"
    device_ip: "172.14.1.8"
    streaming_preset: "medium"
    
  # Unity Editor / Desktop 테스트용
  "UNITY_EDITOR":
    owner: "developer"
    device_ip: "127.0.0.1"  # 로컬 테스트
    streaming_preset: "medium"
    
  "MSI":
    owner: "dongjune_chang"
    device_ip: "127.0.0.1"
    streaming_preset: "high"